### ISSUE TITLE
comments are yellow

### ISSUE THREAD

**Issue by WhoIsSethDaniel** [ribru17/bamboo.nvim#2]
Everywhere in the `highlights.lua` file comments seems to be `c.grey`.  However, when defining `@comment` they are set to `c.bg_yellow`. Was this a mistake?

I attempted to overwrite this in the `setup()` doing this:

```
require('bamboo').setup {
  highlights =  {
   ['@comment'] = { fg = '$grey' },
  }
}
```

but I still get yellow comments...once semantic tokens come in from the language server. For now I've changed the code to `c.grey` in `highlights.lua`.

I like the theme, except for comments.

**Comment by ribru17** [comment]
Thanks for reporting, I'll take a look at the semantic tokens overriding the user customizations, this should not happen. The yellow comments, however, are intentional for better contrast and readability. This is mentioned briefly in the README. I will be changing all other references of grey comments to yellow, seems I missed a bunch of occurrences. But anyway you should be able to change them to your liking without semantic tokens interfering. I will get working on this soon

**Comment by WhoIsSethDaniel** [comment]
Thank you for the explanation.

**Comment by ribru17** [comment]
Of course. This should be fixed now, let me know if you still get any issues with the custom highlighting

**Comment by WhoIsSethDaniel** [comment]
worked great. Thank you.
